// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hymylaekwonalmsrvhmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bXlsYWVrd29uYWxtc3J2aG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzU2MzEsImV4cCI6MjA2NDk1MTYzMX0.Gl9GFJvWqEBdXfFvDZJVNRpbFF5vzsks9zL_zp_rKY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);